# Generated by Django 2.2.10 on 2022-01-17 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('start_date', models.DateTimeField(verbose_name='start_date')),
                ('end_data', models.DateTimeField(verbose_name='end_data')),
                ('description', models.TextField(verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=250, verbose_name='question_text')),
                ('question_type', models.CharField(choices=[('text answer', 'text answer'), ('single choice answer', 'single choice answer'), ('multiple choice answer', 'multiple choice answer')], max_length=50, verbose_name='question_type')),
                ('survey_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_surveys.Survey')),
            ],
        ),
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices_answer', models.CharField(max_length=250, verbose_name='choices_answer')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_surveys.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='user_id')),
                ('answer', models.CharField(max_length=250, verbose_name='answer')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_surveys.Question')),
                ('survey_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_surveys.Survey')),
            ],
        ),
    ]
