# Generated by Django 2.2.10 on 2022-01-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('Text answer', 'Text answer'), ('Single choice answer', 'Single choice answer'), ('Multiple choice answer', 'Multiple choice answer')], max_length=50, verbose_name='question_type'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='end_data',
            field=models.DateField(verbose_name='end_data'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='start_date',
            field=models.DateField(verbose_name='start_date'),
        ),
    ]
